# Generated by Django 5.0.6 on 2024-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
